### ISSUE TITLE
Fully activated device gets stripped with license every once in a while v5.1.2

### ISSUE THREAD

**Issue by R4CKPH** [AdoPiSoft/Releases#23]
As stated, every once in a while some of my machine gets stripped out of their activation, I have to key it in again or reboot the machine to fix it. v5.1.2

**Comment by yancabz** [comment]
same issue here,, broken sdcard, liscense revoke activate revoke activate again and again,

**Comment by adonespitogo** [comment]
Hello,

Our team is investigating this issue. Most of the users that reported this issue have not encountered this again after some updates to our server. If you are still having this issue, please email your `Device ID` and `License Key` to me adones@adopisoft.com so that our team can trace your issue.
