### ISSUE TITLE
CRITICAL scheduled (cron) reboot issue 5.1.4

### ISSUE THREAD

**Issue by roybugsme** [AdoPiSoft/Releases#39]
Boot progress stuck at 0% after a scheduled reboot.

• Updated from 5.1.3 to 5.1.4
• No other settings changed (including captive portal design).
• DHCP working but No Internet connection.

**Comment by nelfox07** [comment]
As per my experience, it only happens when you have several VLANs in your network. For instance, I have six VLANs, and it takes 1 to 2 minutes for the machine to boot. Whether by manual reboot or by cron, I am using a Dell i3 7th Gen with 128 GB of RAM and 8 GB of ROM. Same problem with my RPI 3B+ with the same network configurations.

**Comment by roybugsme** [comment]
I only have 2 VLANs: Tagged 22 (Vendo), Untagged 28 (Internet). In manual reboots it does successfully boot up, but in scheduled reboot it fails to boot up, I have to unplug and re-plug the vendo for it to boot up successfully. I downgraded back to 5.1.3 because sometimes I fail to check if the vendo is alive or not. Downtime = lost potential revenue & lower customer satisfaction. In 5.1.3 and 5.1.2 I have never experienced these wierd failed reboots.

**Comment by roybugsme** [comment]
@nelfox07 you were right, it was a wierd VLAN issue. I just recently changed VLAN configuration, and it happened even on 5.1.3. What a F-ing annoying bug, lipat na lang ako LPB, allergic pala to sa multi-VLAN setups, tama naman config ko.
